liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: "%kernel.root_dir%/../public/img"
        cache_prefix: media/cache
  filter_sets:
    cache: ~
    my_thumb:
      quality: 100
      filters:
        thumbnail: { size: [350, 350], mode: outbound }
